name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'  # Set the node version for the project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Build the React app
      - name: Build React app
        run: |
          CI=false npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Target branch
          folder: build    # Output folder of React App

